### ISSUE TITLE
Do not pull ptBR subs

### ISSUE THREAD

**Issue by Kstilho** [anidl/multi-downloader-nx#159]
Version: 1.0.3 - Funimation subtitle font.

Comand: ./aniDL --service 'funi' -s 1072618 -e 1 --allSubs --allDubs --fileName '${showTitle}/[GuedesFlix] ${showTitle} - ${season}E${episode} - ${title} [${height}p]' --nocleanup -q0 

![image](https://user-images.githubusercontent.com/93347339/141026946-40eb7800-7cd6-44af-b1de-200df295d1c7.png)

can't get the subtitle pt br
![image](https://user-images.githubusercontent.com/93347339/141027070-deec5e95-2fb8-4129-9f02-ad1dd72fa05f.png)

if the subtitle problem is a geolocation I can download it on another machine. But is there any option to put the subtitle file inside the folder of other files and it be included in the mux?
![image](https://user-images.githubusercontent.com/93347339/141027352-21be61df-f16b-46ed-90ff-88d75c422fb5.png)

I tried with the above command adding --mks but it didn't work
Thanks!

**Comment by STRATOS99K** [comment]
Funi tamayomi Uncut only has english subs, you would need to DL the simulcast version for multi

**Comment by Kstilho** [comment]
> Funi tamayomi Uncut only has english subs, you would need to DL the simulcast version for multi

thank you very much it helped a lot
If possible look at this show -s 94310 the flag --simul did not result in other subtitles

**Comment by STRATOS99K** [comment]
> > Funi tamayomi Uncut only has english subs, you would need to DL the simulcast version for multi
> 
> thank you very much it helped a lot If possible look at this show -s 94310 the flag --simul did not result in other subtitles

-s 1072618 -e 1 -q 0 --allSubs --dub jaJP --simul --novids --noaudio that gave me all available subs, I got Eng, Spa, PT

**Comment by CMoranO** [comment]
Hello, I'm facing a similar issue, but with some spanish dub and subtitles.

Version: 2.0.6

Command:
node index.js --service funi -s 1400038  --dub esLA -q 7 -e 4

output
![image](https://user-images.githubusercontent.com/19246886/144700608-bbcc04db-f35c-4128-b8fc-28d275ec57e3.png)

The script fails to detect esLA dubs in episode 04 and 05, both are available on the website 

Something similar happens with some spanish subtitle tracks.

Command:
node index.js --service funi -s 1400038  --dub jaJP --subLang esLA -e 6 -q 7 

output
![image](https://user-images.githubusercontent.com/19246886/144700920-e93a91fa-2af5-4d4c-a495-6e4ad11b4395.png)

The script uses the eng subtitles instead of spa in some cases, spanish subtitle is also available on the website (--simul doesn't work for me).

![image](https://user-images.githubusercontent.com/19246886/144701103-86a96783-9cce-4ff8-874b-456d26a83257.png)

I have facing this issue in other shows like Noragami [#19754] episode 5 or Moriarty the Patriot [#1174922] episode 12.

Thank you for your work, if more details are needed, I will be glad to provide them.
