### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by rudesniper44444** [anidl/multi-downloader-nx#218]
### Program version

2.0.15

### Service

Crunchyroll

### Command used

.\aniDL.exe --service crunchy -s GRJ0VKG4Y -e 1 -q 1  --dlsubs en

### Show ID

GRJ0VKG4Y 

### Episode

1

### Console Output

![image](https://user-images.githubusercontent.com/97499870/148887983-5fc1cdab-e933-4091-865a-87197bc8235d.png)

hello , does anyone know how to download dubbed and subbed english at the same time 

`.\aniDL.exe --service crunchy -s GRQ40VJ7Y -e 1 -q 1  --dlsubs en
`

when  i use this command i can only download either the dubbed or subbed i can't do both , and when i use --dlsubs en on sub version it works fine but i can't get the dubbed version and when i use --dlsubs en on dubbed it downloads the eng subbed but the subtitle doesn't work .

**Comment by rudesniper44444** [comment]
> ### Program version
> 2.0.15
> 
> ### Service
> Crunchyroll
> 
> ### Command used
> .\aniDL.exe --service crunchy -s GRJ0VKG4Y -e 1 -q 1 --dlsubs en
> 
> ### Show ID
> GRJ0VKG4Y
> 
> ### Episode
> 1
> 
> ### Console Output
> ![image](https://user-images.githubusercontent.com/97499870/148887983-5fc1cdab-e933-4091-865a-87197bc8235d.png)
> 
> hello , does anyone know how to download dubbed and subbed english at the same time
> 
> `.\aniDL.exe --service crunchy -s GRQ40VJ7Y -e 1 -q 1 --dlsubs en `
> 
> when i use this command i can only download either the dubbed or subbed i can't do both , and when i use --dlsubs en on sub version it works fine but i can't get the dubbed version and when i use --dlsubs en on dubbed it downloads the eng subbed but the subtitle doesn't work .
> 
> ### Additional Information
> _No response_

Hello guys? , any help is much appreciated

**Comment by izu-co** [comment]
Please don't be impassioned, we are putting our free time into this free project, and said time is quite rare under the week.

As for your request. Crunchyroll makes one season for every little language. There is a system I put in place a while ago where you can use the `Z:ID` id from the parent of all other seasons. Just try `--srz GYX04955R` in your case. 

You can use it to download multiple dubs from one show, although you might encounter some issue since this feature is fairly new.

**Comment by rudesniper44444** [comment]
.\aniDL.exe --service crunchy --srz GRQ40VJ7Y -e 1 -q 1  --dlsubs en
