### ISSUE TITLE
Don't download the entire season using SRZ command

### ISSUE THREAD

**Issue by Stesmus** [anidl/multi-downloader-nx#273]
### Program version

3.0.2

### Operating System

Windows

### Type

Cli

### Service

Crunchyroll

### Command used

anidl --service crunchy --srz G4PH0WMEX --all --allDubs --novids --noaudio --fileName "${showTitle} [${season}-${episode}]"

### Show ID

G4PH0WMEX

### Episode

All

### Console Output

=== Multi Downloader NX 3.0.2 ===

[INFO] USER: *** (***@gmail.com)
[INFO] Your Country: ***

[Z:G4PH0WMEX] High Guardian Spice (Seasons: 1, EPs: 12) [DUB]
  [S:G6Q4CZD4P] High Guardian Spice (Season: 1) [DUB]
[INFO] USER: *** (***@gmail.com)
[INFO] Your Country: ***

------------------------------

### Additional Information

```Text
And then nothing happens, I tried everything. Why doesn't it download via the SRZ command? Works with some. It's inconvenient to extract manually depending on the season using -s.

This is just an example of such a case. Thanks anyway.
```

**Comment by izu-co** [comment]
First, a few words about `--srz`. Since Crunchyroll splits everything in different season and sometimes fail to label the season right (e.g. Japanese → Season 2, Dubs → Season 1) `--srz` **`tries`** to make it possible to download different dubs and merge them with the continence of the downloader. It might fail, tho.

That said, I will look at your case and respond later. It is possible that it is a problem with `--srz`.

**Comment by Stesmus** [comment]
You respond quickly. I'm amazed. Thanks.

**Comment by izu-co** [comment]
This should be resolved with the newest commit. (A new release will be made)
